#!/bin/bash

set -e

usage() {
	echo "Usage:"
	echo "extractfile [package] [filename]"
	exit 0
}

getFileFromTGZ() {

	P=$1
	TGZTMP=/tmp/tgz$$
	mkdir -p $TGZTMP
	cp $P $TGZTMP
	cd $TGZTMP
	FILE_LOCATION=`tar -tzf $P | grep "\/$FILE\$"`
	tar xzf $P $FILE_LOCATION

	cd $CURDIR
	cp $TGZTMP/$FILE_LOCATION ./
	
	rm -Rf $TGZTMP
}
getFileFromDeb() {

	DEBTMP=/tmp/deb$$
	mkdir -p $DEBTMP
	cp $PACKAGE $DEBTMP
	cd $DEBTMP
	ar -vx $PACKAGE_FILENAME >/dev/null 2>/dev/null

	getFileFromTGZ $DEBTMP/data.tar.gz

	#cleanup
	rm -Rf $DEBTMP

}

getFileFromRpm() {

	RPMTMP=/tmp/rpm$$
	mkdir -p $RPMTMP
	cd $RPMTMP

	FILE_LOCATION=`rpm -qlp $PACKAGE| grep "\/$FILE\$"`
	rpm2cpio $PACKAGE| cpio -ivd .$FILE_LOCATION >/dev/null 2>&1

	cd $CURDIR

	cp $RPMTMP/$FILE_LOCATION ./
	rm -Rf $RPMTMP

}

getFileFromZip() {

	ZIPTMP=/tmp/zip$$
	mkdir $ZIPTMP

	cd $ZIPTMP
	FILE_LOCATION=`unzip -l $PACKAGE | awk '{print $4}' | grep "\/$FILE\$"`

	unzip -p $PACKAGE $FILE_LOCATION > $FILE

	cd $CURDIR
	cp $ZIPTMP/$FILE ./

	rm -Rf $ZIPTMP
}

PACKAGE=$1
FILE=$2
EXT=${PACKAGE: -3}

if [ "$EXT" = ".gz" ]; then
	EXT=${PACKAGE: -6}
fi

CURDIR=`pwd`

if ! [ "$PACKAGE" ]; then
	usage
fi

case $EXT in
	deb)
		getFileFromDeb
		;;
	rpm)
		getFileFromRpm
		;;
	tar.gz)
		getFileFromTGZ $PACKAGE
		;;
	zip)
		getFileFromZip
		;;
	*)
		>&2 echo "Unknown package type"
		exit 1
		;;
esac
