#!/bin/bash

set -e
# Script to start development version of RIDE

if [ -d "${HOME}/Development/RideJS" ]; then

	RIDE_LOCATION=${HOME}/Development/RideJS

	# Pass the arguments on to Ride
	cd $RIDE_LOCATION
	# Update sources
	git pull
	# build Ride
	./dist.sh
	# run Ride with the listen arguments - carry on.
	./build/ride/linux64/ride $@ &

elif [ -d "${HOME}/Ride" ]; then

	#run RIDE from user home directory
	${HOME}/Ride/ride $@ &
fi
