#!/bin/bash

set -e
# Script to start development version of RIDE

if [ -d "${HOME}/Development/ride" ]; then

	RIDE_LOCATION=${HOME}/Development/ride

	# Pass the arguments on to Ride
	cd $RIDE_LOCATION
	if ! ps -A | grep -v $$ | grep ride; then
		echo "building Ride"
		# Update sources
		git pull
		npm i
		# build Ride
		./dist.sh linux64
	fi
	# run Ride with the listen arguments - carry on.
	./build/ride/linux64/ride $@ &

elif [ -d "${HOME}/Ride" ]; then

	#run RIDE from user home directory
	${HOME}/Ride/ride $@ &
fi
